//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketsSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedTickets
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Pasport { get; set; }
        public string TicketKod { get; set; }
        public string Trip { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public string VanType { get; set; }
        public decimal Price { get; set; }
    }
}
