//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketsSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public string TripStart { get; set; }
        public string TripFinish { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public Nullable<int> CompartmantTicketsCount { get; set; }
        public decimal CompartmentPrice { get; set; }
        public Nullable<int> ReservedSeatTicketsCount { get; set; }
        public decimal ReservedSeatPrice { get; set; }
        public string TicketKod { get; set; }
    }
}
